<#import "macros.ftl" as my>
<#assign attrJavaPackage = my.getJavaPackage() >
<#assign objectName = object.getName() >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

public enum ${objectName} {	
<#list object.getValues() as value >
	<#assign name = value.getName()?upper_case >
	${name}<#if value_has_next>,<#else>;</#if>
</#list>
}