<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".exception" >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

/**
 * runtime exeptions thrown by the server side 
 */
public class ServerException extends RuntimeException {
	private static final long serialVersionUID = 1L;
	
	/**
	 * can't be created by default
	 */
	protected ServerException() {
	}
}
