<#import "macros.ftl" as my>
<#assign attrJavaPackage = my.getJavaPackage() >
<#assign objectName = object.getName() >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

/**
 * type ${objectName}
 */
public class ${objectName}${my.baseType( object )} {
	private static final long serialVersionUID = 1L;
<@my.classMembers items=object.getMembers() />
<@my.classGettersSetters items=object.getMembers() className=objectName />

<@my.hashCodeFunction items=object.getAllMembers() />

<@my.equalsFunction items=object.getAllMembers() className=objectName />

<@my.toStringFunction items=object.getAllMembers() className=objectName />
}