<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".exception" >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

/**
 * Exception thrown if the security credential did expire
 */
public class AccessExpiredException extends ServerException {
	private static final long serialVersionUID = 1L;
	protected String reason;
	
	public AccessExpiredException() {
	}
	
	public void setReason( String reason ) {
		this.reason = reason;
	}
	
	public String getReason() {
		return reason;
	}
	
	public AccessExpiredException withReason( String reason ) {
		this.reason = reason;
		return this;
	}
	
	@Override
    public String getMessage() {
        return reason;
    }
}
