<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".call" >
<#assign objectName = object.getName() >
<#assign className = 'Call'+ objectName >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

public final class ${className} {

<#list object.getFunctions() as function >
	<#assign fname = function.getName() >
	<#assign ARfname = fname?cap_first + "Request"  >
	<#assign APfname = fname?cap_first + "Response"  >
/**************************************************************************************************************
 * function ${ARfname}
 * 
 **************************************************************************************************************/
public static final class ${ARfname} {
<@my.classMembers items=function.getArguments() />
<@my.classGettersSetters items=function.getArguments() className=ARfname />

<@my.hashCodeFunction items=function.getArguments() />

<@my.equalsFunction items=function.getArguments() className=ARfname />

<@my.toStringFunction items=function.getArguments() className=ARfname />

<@my.readMemberFunction items=function.getArguments() className=ARfname classPackage=thisJavaPackage+'.'+className />

<@my.writeMembersFunction items=function.getArguments() className=ARfname baseClassName='' classPackage=thisJavaPackage+'.'+className />

<@my.memberReaders items=function.getArguments() className=ARfname classPackage=thisJavaPackage+'.'+className />
}

/**************************************************************************************************************
 * function ${APfname}
 * 
 **************************************************************************************************************/
public static final class ${APfname} {

}
</#list>
}