<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".json.exception" >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

import ${modelJavaPackage}.exception.ValidationException;
import ${modelJavaPackage}.u.Lib.JsonReader;
import ${modelJavaPackage}.u.Lib.JsonWriter;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.JsonGenerator;

public class ValidationExceptionSerializer {
	public static final String className = "exception.validation";
	
	/**
	 * the reader
	 */
	public static final JsonReader<ValidationException> READER = new JsonReader<ValidationException>() {
		public ValidationException read( JsonParser jp ) throws IOException {			
			ValidationException result = new ValidationException();
			
			while( jp.nextToken() == JsonToken.FIELD_NAME ) {
				String fieldName = jp.getCurrentName();
				jp.nextToken();
				if( "reason".equals( fieldName ) ) {
					result.setReason( jp.getText() );
				} else if( "code".equals( fieldName ) ) {
					result.setCode( jp.getText() );
				} else {
					jp.skipChildren(); 					
				}
			}
			
			return result;
		}
	};
	
	/**
	 * the writer
	 */
	public static final JsonWriter WRITER = new JsonWriter() {
		public void write( JsonGenerator jg, Object object ) throws IOException {
			ValidationException cobj = (ValidationException) object;
			jg.writeStartObject();
			jg.writeFieldName( "__type" );
			jg.writeString( className );

			if( cobj.getCode() != null ) {
				jg.writeFieldName( "code" );
				jg.writeString( cobj.getCode() );
			}
			
			if( cobj.getReason() != null ) {
				jg.writeFieldName( "reason" );
				jg.writeString( cobj.getReason() );
			}
			
			jg.writeEndObject();
		}
	};
}