<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".json" >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

import java.io.IOException;
import java.util.List;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.JsonParseException;

public class datetimeSerializer {
	/**
	 * write map value
	 */
	public static void writeValue( JsonGenerator jg, String name, Map<String, LocalDateTime> map, String src ) throws IOException {
		if( map != null ) {
			jg.writeFieldName( name );
			jg.writeStartObject();
			for( Map.Entry<String, LocalDateTime> element : map.entrySet() ) {
				if( element.getKey() == null ) {
					throw new IllegalArgumentException( String.format( "map element '%s.%s' has null key", src, name ) );
				}
				if( element.getValue() == null ) {
					throw new IllegalArgumentException( String.format( "map element '%s.%s.%s' has null value", src, name, element.getKey() ) );
				}
				jg.writeFieldName( element.getKey() );
				jg.writeString( element.getValue().toString() );
			}
			jg.writeEndObject();
		}
	}
	
	/**
	 * write array value
	 */
	public static void writeValue( JsonGenerator jg, String name, List<LocalDateTime> array, String src ) throws IOException {
		if( array != null ) {
			jg.writeFieldName( name );
			jg.writeStartArray();
			for( LocalDateTime element : array ) {
				if( element == null ) {
					throw new IllegalArgumentException( String.format( "array '%s.%s' has null element", src, name ) );
				}
				jg.writeString( element.toString() );
			}
			jg.writeEndArray();
		}
	}
	
	/**
	 * write value
	 */
	public static void writeValue( JsonGenerator jg, String name, LocalDateTime value, String src ) throws IOException {
		if( value != null ) {
			jg.writeFieldName( name );
			jg.writeString( value.toString() );
		}
	}
	
	/**
	 * read LocalDateTime value
	 */
	public static LocalDateTime readValue( JsonParser jp, String name, String src ) throws IOException {
		if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
			return null;
		}
		return LocalDateTime.parse( jp.getText() );
	}
	
	/**
	 * read LocalDateTime value array
	 */
	public static List<LocalDateTime> readValueArray( JsonParser jp, String name, String src ) throws IOException {
		if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
			return null;
		}
		
		if( !jp.isExpectedStartArrayToken() ) {
			throw new JsonParseException( jp,
				String.format( "expected array for '%s.%s'", src, name )
			);
		}
		
		List<LocalDateTime> list = new ArrayList<LocalDateTime>();
		while (jp.nextToken() != JsonToken.END_ARRAY) {
			if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
				throw new JsonParseException( jp,
					String.format( "array '%s.%s' has null value", src, name )
				);
			}
			list.add( LocalDateTime.parse( jp.getText() ) );
		}
		
		return list;
	}

	/**
	 * read LocalDateTime value map
	 */
	public static Map<String, LocalDateTime> readValueMap( JsonParser jp, String name, String src) throws IOException {
		if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
			return null;
		}

		if( !jp.isExpectedStartObjectToken() ) {
			throw new JsonParseException( jp,
				String.format( "expected object for '%s.%s'", src, name )
			);
		}
		
		Map<String, LocalDateTime> map = 
				new HashMap<String, LocalDateTime>();
				
		while (jp.nextToken() == JsonToken.FIELD_NAME) {
			String fieldName = jp.getCurrentName();
			jp.nextToken();
			if( jp.getCurrentToken() != JsonToken.VALUE_NULL ) {
				map.put( fieldName, LocalDateTime.parse( jp.getText() ) );
			}
		}
		
		return map;
	}
}
