<#import "macros.ftl" as my>
<#assign modelJavaPackage = my.getJavaPackage() >
<#assign thisJavaPackage = modelJavaPackage + ".u" >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${thisJavaPackage};

import java.io.IOException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import java.util.UUID;
import java.time.LocalDateTime;

public class Lib {	
	public interface JsonWriter {
		void write( JsonGenerator jg, Object object ) throws IOException;
	}

	public interface JsonReader<T> {
		T read( JsonParser jp ) throws IOException;
	}
	
	public interface MemberReader<T> {
		void read( JsonParser jp, T object ) throws IOException;
	}

	public static UUID parseUUID( JsonParser jp ) throws IOException {
		if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
			return null;
		}
		return UUID.fromString( jp.getText() );
	}	
	
	public static LocalDateTime parseDate( JsonParser jp ) throws IOException {
		if( jp.getCurrentToken() == JsonToken.VALUE_NULL ) {
			return null;
		}
		return LocalDateTime.parse( jp.getText() );
	}
}